  version: '3.6'
  services:
    gitlab:
      image: gitlab/gitlab-ce:nightly
      container_name: gitlab
      restart: always
      hostname: 'localhost'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          # Add any other gitlab.rb configuration here, each on its own line
          external_url 'http://localhost'
          gitlab_rails['omniauth_allow_single_sign_on'] = [ 'auth0' ]
          gitlab_rails['omniauth_providers'] = [
            {
              name: "auth0",
              # label: "Provider name", # optional label for login button, defaults to "Auth0"
              args: {
                client_id: "test",
                client_secret: "test",
                domain: "<test>.us.auth0.com",
                scope: "openid profile email"
              }
            }
          ]
      ports:
        - '80:80'
        - '443:443'
        - '2424:22'
      volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'
      shm_size: '256m'

